export const ActionTypes = {
    UPDATE_WORD: "UPDATE_WORD",
    GET_WORD: ' GET_WORD',
    GET_WORDS: 'GET_WORDS',
    ADD_WORD: ' ADD_WORD',
    DELETE_WORD: ' DELETE_WORD',
    LOAD_WORDS_SUCCESS: 'LOAD_WORDS_SUCCESS',
    LOAD_WORDS_ERROR: 'LOAD_WORDS_ERROR',
};